import { Component } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-locate-us',
  templateUrl: './locate-us.component.html',
  styleUrls: ['./locate-us.component.css']
})
export class LocateUsComponent {
  showFlag = true;
  hide = true;
  items = [{ name: 'ATM - Mumbai - Shivaji chowk kashimira mira road', address: '(Non-Metro Location)  Gala no 23 apna bldg. chatrapati Shivaji chowk Shivaji chowk kashimira mira road kashimira mira road east 401107', contact: 'Phone No : 1860 266 2666', hours: 'Hours: 12:00 AM To 11:59 PM' },
  { name: 'Kotak Mahindra Bank Mira Bhayander Branch IFSC Code kkbk0000649', address: 'Kotak Mahindra Bank Ltd. E Wing, Latif Park,Mira Bhayandar Road; Mira Road (E),Thane, Maharashtra - 401107', contact: 'Tel -(022) 28120740,46-49 Phone No : 1860 266 2666', hours: 'Hours: Weekday Timing 9.30 am to 16.30 pm' }];
  filteredItems: { name: string, address: string, contact: string, hours: string }[] = [];
  searchText = '';
  filterItems() {
    this.hide = false;
    this.showFlag = false;
    if (this.searchText) {
      this.filteredItems = this.items.filter(item => {
        return item.name.toLowerCase().includes(this.searchText.toLowerCase())
          || item.address.toLowerCase().includes(this.searchText.toLowerCase())
          || item.contact.toLowerCase().includes(this.searchText.toLowerCase())
          || item.hours.toLowerCase().includes(this.searchText.toLowerCase())
      });
    }
    else {
      this.filteredItems = [];
    }
  }

  selectedValue: string = '';
  stateList: Array<any> =
    [
      {
        name: 'ANDHRA PRADESH', cities: ['Adoni',
          'Amaravati',
          'Anantapur',
          'Chandragiri',
          'Chittoor',
          'Dowlaiswaram',
          'Eluru',
          'Guntur',
          'Kadapa',
          'Kakinada',
          'Kurnool',
          'Machilipatnam',
          'Nagarjunakoṇḍa',
          'Rajahmundry',
          'Srikakulam',
          'Tirupati',
          'Vijayawada',
          'Visakhapatnam',
          'Vizianagaram',
          'Yemmiganur']
      },
      { name: 'ARUNANCHAL PRADESH', cities: ['Itanagar'] },
      {
        name: 'ASSAM', cities: ['Dhuburi',
          'Dibrugarh',
          'Dispur',
          'Guwahati',
          'Jorhat',
          'Nagaon',
          'Sivasagar',
          'Silchar',
          'Tezpur',
          'Tinsukia']
      },
      {
        name: 'BIHAR', cities: ['Ara',
          'Barauni',
          'Begusarai',
          'Bettiah',
          'Bhagalpur',
          'Bihar Sharif',
          'Bodh Gaya',
          'Buxar',
          'Chapra',
          'Darbhanga',
          'Dehri',
          'Dinapur Nizamat',
          'Gaya',
          'Hajipur',
          'Jamalpur',
          'Katihar',
          'Madhubani',
          'Motihari',
          'Munger',
          'Muzaffarpur',
          'Patna',
          'Purnia',
          'Pusa',
          'Saharsa',
          'Samastipur',
          'Sasaram',
          'Sitamarhi',
          'Siwan']
      },
      { name: 'CHANDIGARH', cities: ['Chandigarh'] },
      {
        name: 'CHHATTISGARH', cities: ['Ambikapur',
          'Bhilai',
          'Bilaspur',
          'Dhamtari',
          'Durg',
          'Jagdalpur',
          'Raipur',
          'Rajnandgaon']
      },
      { name: 'DADRA & NAGAR HAVELI', cities: ['Silvassa'] },
      { name: 'DAMAN AND DIU', cities: ['Daman', 'Diu'] },
      {
        name: 'DELHI', cities: ['Delhi',
          'New Delhi']
      },
      {
        name: 'GOA', cities: ['Madgaon',
          'Panaji']
      },
      {
        name: 'GUJARAT', cities: ['Ahmadabad',
          'Amreli',
          'Bharuch',
          'Bhavnagar',
          'Bhuj',
          'Dwarka',
          'Gandhinagar',
          'Godhra',
          'Jamnagar',
          'Junagadh',
          'Kandla',
          'Khambhat',
          'Kheda',
          'Mahesana',
          'Morbi',
          'Nadiad',
          'Navsari',
          'Okha',
          'Palanpur',
          'Patan',
          'Porbandar',
          'Rajkot',
          'Surat',
          'Surendranagar',
          'Valsad',
          'Veraval']
      },
      {
        name: 'HARYANA', cities: ['Ambala',
          'Bhiwani',
          'Chandigarh',
          'Faridabad',
          'Firozpur Jhirka',
          'Gurugram',
          'Hansi',
          'Hisar',
          'Jind',
          'Kaithal',
          'Karnal',
          'Kurukshetra',
          'Panipat',
          'Pehowa',
          'Rewari',
          'Rohtak',
          'Sirsa',
          'Sonipat']
      },
      {
        name: 'HIMACHAL PRADESH', cities: ['Bilaspur',
          'Chamba',
          'Dalhousie',
          'Dharmshala',
          'Hamirpur',
          'Kangra',
          'Kullu',
          'Mandi',
          'Nahan',
          'Shimla',
          'Una']
      },
      {
        name: 'JAMMU & KASHMIR', cities: ['Anantnag',
          'Baramula',
          'Doda',
          'Gulmarg',
          'Jammu',
          'Kathua',
          'Punch',
          'Rajouri',
          'Srinagar',
          'Udhampur']
      },
      {
        name: 'JHARKHAND', cities: ['Bokaro',
          'Chaibasa',
          'Deoghar',
          'Dhanbad',
          'Dumka',
          'Giridih',
          'Hazaribag',
          'Jamshedpur',
          'Jharia',
          'Rajmahal',
          'Ranchi',
          'Saraikela']
      },
      {
        name: 'KARNATAKA', cities: ['Badami',
          'Ballari',
          'Bengaluru',
          'Belagavi',
          'Bhadravati',
          'Bidar',
          'Chikkamagaluru',
          'Chitradurga',
          'Davangere',
          'Halebid',
          'Hassan',
          'Hubballi-Dharwad',
          'Kalaburagi',
          'Kolar',
          'Madikeri',
          'Mandya',
          'Mangaluru',
          'Mysuru',
          'Raichur',
          'Shivamogga',
          'Shravanabelagola',
          'Shrirangapattana',
          'Tumakuru',
          'Vijayapura']
      },
      {
        name: 'KERALA', cities: ['Alappuzha',
          'Vatakara',
          'Idukki',
          'Kannur',
          'Kochi',
          'Kollam',
          'Kottayam',
          'Kozhikode',
          'Mattancheri',
          'Palakkad',
          'Thalassery',
          'Thiruvananthapuram',
          'Thrissur']
      },
      {
        name: 'MADHYA PRADESH', cities: ['Balaghat',
          'Barwani',
          'Betul',
          'Bharhut',
          'Bhind',
          'Bhojpur',
          'Bhopal',
          'Burhanpur',
          'Chhatarpur',
          'Chhindwara',
          'Damoh',
          'Datia',
          'Dewas',
          'Dhar',
          'Dr. Ambedkar Nagar (Mhow)',
          'Guna',
          'Gwalior',
          'Hoshangabad',
          'Indore',
          'Itarsi',
          'Jabalpur',
          'Jhabua',
          'Khajuraho',
          'Khandwa',
          'Khargone',
          'Maheshwar',
          'Mandla',
          'Mandsaur',
          'Morena',
          'Murwara',
          'Narsimhapur',
          'Narsinghgarh',
          'Narwar',
          'Neemuch',
          'Nowgong',
          'Orchha',
          'Panna',
          'Raisen',
          'Rajgarh',
          'Ratlam',
          'Rewa',
          'Sagar',
          'Sarangpur',
          'Satna',
          'Sehore',
          'Seoni',
          'Shahdol',
          'Shajapur',
          'Sheopur',
          'Shivpuri',
          'Ujjain',
          'Vidisha']
      },
      {
        name: 'MAHARASHTRA', cities: ['Ahmadnagar',
          'Akola',
          'Amravati',
          'Aurangabad',
          'Bhandara',
          'Bhusawal',
          'Bid',
          'Buldhana',
          'Chandrapur',
          'Daulatabad',
          'Dhule',
          'Jalgaon',
          'Kalyan',
          'Karli',
          'Kolhapur',
          'Mahabaleshwar',
          'Malegaon',
          'Matheran',
          'Mumbai',
          'Nagpur',
          'Nanded',
          'Nashik',
          'Osmanabad',
          'Pandharpur',
          'Parbhani',
          'Pune',
          'Ratnagiri',
          'Sangli',
          'Satara',
          'Sevagram',
          'Solapur',
          'Thane',
          'Ulhasnagar',
          'Vasai-Virar',
          'Wardha',
          'Yavatmal']
      },
      { name: 'MANIPUR', cities: ['Imphal'] },
      {
        name: 'MEGHALAYA', cities: ['Cherrapunji',
          'Shillong']
      },
      {
        name: 'ODISHA', cities: ['Balangir',
          'Baleshwar',
          'Baripada',
          'Bhubaneshwar',
          'Brahmapur',
          'Cuttack',
          'Dhenkanal',
          'Kendujhar',
          'Konark',
          'Koraput',
          'Paradip',
          'Phulabani',
          'Puri',
          'Sambalpur',
          'Udayagiri']
      },
      {
        name: 'PUDUCHERRY', cities: ['Karaikal',
          'Mahe',
          'Puducherry',
          'Yanam']
      },
      {
        name: 'PUNJAB', cities: ['Amritsar',
          'Batala',
          'Chandigarh',
          'Faridkot',
          'Firozpur',
          'Gurdaspur',
          'Hoshiarpur',
          'Jalandhar',
          'Kapurthala',
          'Ludhiana',
          'Nabha',
          'Patiala',
          'Rupnagar',
          'Sangrur']
      },
      {
        name: 'RAJASTHAN', cities: ['Abu',
          'Ajmer',
          'Alwar',
          'Amer',
          'Barmer',
          'Beawar',
          'Bharatpur',
          'Bhilwara',
          'Bikaner',
          'Bundi',
          'Chittaurgarh',
          'Churu',
          'Dhaulpur',
          'Dungarpur',
          'Hanumangarh',
          'Jaipur',
          'Jaisalmer',
          'Jalor',
          'Jhalawar',
          'Jhunjhunu',
          'Jodhpur',
          'Kishangarh',
          'Kota',
          'Merta',
          'Nagaur',
          'Nathdwara',
          'Pali',
          'Phalodi',
          'Pushkar',
          'Sawai Madhopur',
          'Shahpura',
          'Sikar',
          'Sirohi',
          'Tonk',
          'Udaipur']
      },
      {
        name: 'SIKKIM', cities: ['Gangtok',
          'Gyalshing',
          'Lachung',
          'Mangan']
      },
      {
        name: 'TAMIL NADU', cities: ['Arcot',
          'Chengalpattu',
          'Chennai',
          'Chidambaram',
          'Coimbatore',
          'Cuddalore',
          'Dharmapuri',
          'Dindigul',
          'Erode',
          'Kanchipuram',
          'Kanniyakumari',
          'Kodaikanal',
          'Kumbakonam',
          'Madurai',
          'Mamallapuram',
          'Nagappattinam',
          'Nagercoil',
          'Palayamkottai',
          'Pudukkottai',
          'Rajapalayam',
          'Ramanathapuram',
          'Salem',
          'Thanjavur',
          'Tiruchchirappalli',
          'Tirunelveli',
          'Tiruppur',
          'Thoothukudi',
          'Udhagamandalam',
          'Vellore']
      },
      {
        name: 'TELANGANA', cities: ['Hyderabad',
          'Karimnagar',
          'Khammam',
          'Mahbubnagar',
          'Nizamabad',
          'Sangareddi',
          'Warangal']
      },
      { name: 'TRIPURA', cities: ['Agartala'] },
      {
        name: 'UTTAR PRADESH', cities: ['Agra',
          'Aligarh',
          'Amroha',
          'Ayodhya',
          'Azamgarh',
          'Bahraich',
          'Ballia',
          'Banda',
          'Bara Banki',
          'Bareilly',
          'Basti',
          'Bijnor',
          'Bithur',
          'Budaun',
          'Bulandshahr',
          'Deoria',
          'Etah',
          'Etawah',
          'Faizabad',
          'Farrukhabad-cum-Fatehgarh',
          'Fatehpur',
          'Fatehpur Sikri',
          'Ghaziabad',
          'Ghazipur',
          'Gonda',
          'Gorakhpur',
          'Hamirpur',
          'Hardoi',
          'Hathras',
          'Jalaun',
          'Jaunpur',
          'Jhansi',
          'Kannauj',
          'Kanpur',
          'Lakhimpur',
          'Lalitpur',
          'Lucknow',
          'Mainpuri',
          'Mathura',
          'Meerut',
          'Mirzapur-Vindhyachal',
          'Moradabad',
          'Muzaffarnagar',
          'Partapgarh',
          'Pilibhit',
          'Prayagraj',
          'Rae Bareli',
          'Rampur',
          'Saharanpur',
          'Sambhal',
          'Shahjahanpur',
          'Sitapur',
          'Sultanpur',
          'Tehri',
          'Varanasi']
      },
      {
        name: 'UTTARAKHAND', cities: ['Almora',
          'Dehra Dun',
          'Haridwar',
          'Mussoorie',
          'Nainital',
          'Pithoragarh']
      },
      {
        name: 'WEST BENGAL', cities: ['Alipore',
          'Alipur Duar',
          'Asansol',
          'Baharampur',
          'Bally',
          'Balurghat',
          'Bankura',
          'Baranagar',
          'Barasat',
          'Barrackpore',
          'Basirhat',
          'Bhatpara',
          'Bishnupur',
          'Budge Budge',
          'Burdwan',
          'Chandernagore',
          'Darjeeling',
          'Diamond Harbour',
          'Dum Dum',
          'Durgapur',
          'Halisahar',
          'Haora',
          'Hugli',
          'Ingraj Bazar',
          'Jalpaiguri',
          'Kalimpong',
          'Kamarhati',
          'Kanchrapara',
          'Kharagpur',
          'Cooch Behar',
          'Kolkata',
          'Krishnanagar',
          'Malda',
          'Midnapore',
          'Murshidabad',
          'Nabadwip',
          'Palashi',
          'Panihati',
          'Purulia',
          'Raiganj',
          'Santipur',
          'Shantiniketan',
          'Shrirampur',
          'Siliguri', ,
          'Siuri',
          'Tamluk',
          'Titagarh']
      }
    ];
  cities: Array<any>;
  changeState(count) {
    this.showFlag = false;
    this.cities = this.stateList.find(con => con.name == count).cities;
  }
}